/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CalculoImpuestoRenta.java
 *
 * Created on 01-jun-2014, 14:14:59
 */
package com.sri.interfaces.iva;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import com.sri.clases.conexion;
import java.sql.*;

/**
 *
 * @author Pablo
 */
public class CalculoImpuestoRenta extends javax.swing.JFrame {

    /** Creates new form CalculoImpuestoRenta */
    public CalculoImpuestoRenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        for (int i = 1970; i < 2015; i++) {
            this.comboAño.addItem(i);
        }
        this.comboAño.setSelectedItem(2014);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboAño = new javax.swing.JComboBox();
        btnCacular = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jLabel26 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lblEgresos = new javax.swing.JLabel();
        lblVB2 = new javax.swing.JLabel();
        lblLibreEgresos = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        lblVB4 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lblIngresos = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lblLibreIngresos = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        lblSueldoTotalIng = new javax.swing.JLabel();
        lblSueldoTotalEgre = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lblEducacion = new javax.swing.JLabel();
        lblAlimentacion = new javax.swing.JLabel();
        lblVivienda = new javax.swing.JLabel();
        lblSalud = new javax.swing.JLabel();
        lblVestimenta = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lblVestimenta1 = new javax.swing.JLabel();
        lblRentaSueldo = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        btnFactVentas = new javax.swing.JButton();
        btnFactCompras = new javax.swing.JButton();
        btnCalcularIVA3 = new javax.swing.JButton();
        btnCalcularIVA6 = new javax.swing.JButton();
        btnCalcularIVA7 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione el año:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setText("Calculo Impuesto a la renta");

        btnCacular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flaticon_562 (1).png"))); // NOI18N
        btnCacular.setText("Calcular");
        btnCacular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCacularActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel26.setText("Actividades empresariales son registro de ingresos y egresos");

        jLabel41.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 204, 51));
        jLabel41.setText("481");

        lblEgresos.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblEgresos.setText("0");

        lblVB2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblVB2.setText("Ingresos");

        lblLibreEgresos.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblLibreEgresos.setText("0");

        jLabel42.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 204, 51));
        jLabel42.setText("491");

        lblVB4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblVB4.setText("Gastos deducibles");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel27.setText("Libre ejercicio profesional");

        jLabel43.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 204, 51));
        jLabel43.setText("511");

        lblIngresos.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblIngresos.setText("0");

        jLabel44.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 204, 51));
        jLabel44.setText("521");

        lblLibreIngresos.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblLibreIngresos.setText("0");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel28.setText("Sueldos, salarios, indemnizaciones y otros ingresos líquidos del trabajo en ralación de dependencia");

        jLabel45.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 204, 51));
        jLabel45.setText("541");

        jLabel46.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 204, 51));
        jLabel46.setText("551");

        lblSueldoTotalIng.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblSueldoTotalIng.setText("0");

        lblSueldoTotalEgre.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblSueldoTotalEgre.setText("0");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel29.setText("Gastos Personales - Educación");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel30.setText("OTRAS DEDUCCIONES Y EXONERACIONES");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel31.setText("Gastos Personales - Alimentación");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel32.setText("Gastos Personales - Salud");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel33.setText("Gastos Personales - Vivienda");

        jLabel47.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 204, 51));
        jLabel47.setText("571");

        jLabel48.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 204, 51));
        jLabel48.setText("572");

        jLabel49.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 204, 51));
        jLabel49.setText("573");

        jLabel50.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 204, 51));
        jLabel50.setText("574");

        jLabel51.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 204, 51));
        jLabel51.setText("575");

        jLabel34.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel34.setText("Gastos Personales - Vestimenta");

        lblEducacion.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblEducacion.setText("0");

        lblAlimentacion.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblAlimentacion.setText("0");

        lblVivienda.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblVivienda.setText("0");

        lblSalud.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblSalud.setText("0");

        lblVestimenta.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblVestimenta.setText("0");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 255));
        jLabel35.setText("(-) Retenciones en la fuente que le realizaron en el ejercicio fiscal");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 255));
        jLabel36.setText("(-) Retenciones en la fuente que le realizaron en el ejercicio fiscal en relacción de dependencia");

        jLabel37.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 255));
        jLabel37.setText("845");

        jLabel38.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 255));
        jLabel38.setText("846");

        lblVestimenta1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblVestimenta1.setText("0");

        lblRentaSueldo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblRentaSueldo.setText("0");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 255));
        jLabel39.setText("Aplicable al período");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30))
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addComponent(lblVB2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(lblVB4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                                                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblSueldoTotalIng, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(19, 19, 19)
                                                .addComponent(lblLibreIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(35, 35, 35))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)))
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLibreEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSueldoTotalEgre, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblVestimenta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEducacion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblVestimenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRentaSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel28))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVB2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVB4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel42)
                                .addComponent(lblIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel41))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel43)
                                .addComponent(lblLibreIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel44)
                                .addComponent(lblLibreEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel45)
                                .addComponent(lblSueldoTotalIng, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblSueldoTotalEgre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel46)))))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(10, 10, 10)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel47)
                    .addComponent(lblEducacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel48)
                    .addComponent(lblSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel49)
                    .addComponent(lblAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel50)
                    .addComponent(lblVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(jLabel34)
                    .addComponent(lblVestimenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel37)
                    .addComponent(lblVestimenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel38)
                    .addComponent(lblRentaSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFactVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FactVentaICO.png"))); // NOI18N
        btnFactVentas.setText("Facturas Ventas");
        btnFactVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactVentasActionPerformed(evt);
            }
        });

        btnFactCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FactCompraICO.png"))); // NOI18N
        btnFactCompras.setText("Facturas Compras");
        btnFactCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactComprasActionPerformed(evt);
            }
        });

        btnCalcularIVA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flaticon_46632 (2).png"))); // NOI18N
        btnCalcularIVA3.setText("Ingresos");
        btnCalcularIVA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularIVA3ActionPerformed(evt);
            }
        });

        btnCalcularIVA6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flaticon_562 (1).png"))); // NOI18N
        btnCalcularIVA6.setText("IVA");
        btnCalcularIVA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularIVA6ActionPerformed(evt);
            }
        });

        btnCalcularIVA7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flaticon_562 (1).png"))); // NOI18N
        btnCalcularIVA7.setText("Impuesto a la renta");
        btnCalcularIVA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularIVA7ActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(72, 72, 72)
                                .addComponent(comboAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(btnCacular))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnFactVentas)
                        .addGap(19, 19, 19)
                        .addComponent(btnFactCompras)
                        .addGap(5, 5, 5)
                        .addComponent(btnCalcularIVA3)
                        .addGap(41, 41, 41)
                        .addComponent(btnCalcularIVA6)
                        .addGap(19, 19, 19)
                        .addComponent(btnCalcularIVA7)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFactVentas)
                    .addComponent(btnFactCompras)
                    .addComponent(btnCalcularIVA3)
                    .addComponent(btnCalcularIVA6)
                    .addComponent(btnCalcularIVA7)
                    .addComponent(btnSalir))
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCacular))
                .addGap(19, 19, 19)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnCacularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCacularActionPerformed
    conexion cc = new conexion();
    Connection cn = (Connection) cc.conexion();
    Statement stmt = null;
    ResultSet rs = null;
    float v1 = 0,v2 = 0,v3 = 0,v4= 0,v5= 0,v6= 0, vt= 0;
    float c1= 0,c2= 0,c3= 0,c4= 0,c5= 0, ct= 0;
    try {
        stmt = (Statement) cn.createStatement();
        //Ventas
        rs = stmt.executeQuery("select sum(subtotal) as id_t from FacturasVentas where year(fechaFactVenta)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=1;");
        while (rs.next()) {
            v1 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(subtotal) as id_t from FacturasVentas where year(fechaFactVenta)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=2;");
        while (rs.next()) {
            v2  = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(valorFactVenta) as id_t from FacturasVentas where year(fechaFactVenta)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=3;");
        while (rs.next()) {
            v3 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(valorFactVenta) as id_t from FacturasVentas where year(fechaFactVenta)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=4;");
        while (rs.next()) {
            v4 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(valorFactVenta) as id_t from FacturasVentas where year(fechaFactVenta)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=5;");
        while (rs.next()) {
            v5 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(valorFactVenta) as id_t from FacturasVentas where year(fechaFactVenta)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=6;");
        while (rs.next()) {
            v6 = rs.getFloat("id_t");
        }
        vt=v1+v2+v3+v4+v5+v6;
        lblIngresos.setText("" + vt);
        
        
        System.out.print("select sum(subtotal) as id_t from FacturasCompras where year(fechaFactCompra)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=1 and tipoGastoFactCompra='Negocio';");
        rs = stmt.executeQuery("select sum(subtotal) as id_t from FacturasCompras where year(fechaFactCompra)= " + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=1 and tipoGastoFactCompra='Negocio';");
        while (rs.next()) {
            c1 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(subtotal) as id_t from FacturasCompras where year(fechaFactCompra)= " + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=2 and tipoGastoFactCompra='Negocio';");
        while (rs.next()) {
            c2 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(subtotal) as id_t from FacturasCompras where year(fechaFactCompra)= " + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=3 and tipoGastoFactCompra='Negocio';");
        while (rs.next()) {
            c3 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(valorFactCompra) as id_t from FacturasCompras where year(fechaFactCompra)= " + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=4 and tipoGastoFactCompra='Negocio';");
        while (rs.next()) {
            c4 = rs.getFloat("id_t");
        }rs = stmt.executeQuery("select sum(valorFactCompra) as id_t from FacturasCompras where year(fechaFactCompra)= " + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=5 and tipoGastoFactCompra='Negocio';");
        while (rs.next()) {
            c5 = rs.getFloat("id_t");
        }
        ct=c1+c2+c3+c4+c5;
        lblEgresos.setText("" + ct);
        
        
        
        
        
        
        rs = stmt.executeQuery("select sum(subtotal) as id_t from FacturasVentas where year(fechafactVenta)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=1 and libre=1;");
        while (rs.next()) {
            v1 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(subtotal) as id_t from FacturasVentas where year(fechafactVenta)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=2 and libre=1;");
        while (rs.next()) {
            v2  = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(valorFactVenta) as id_t from FacturasVentas where year(fechafactVenta)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=3 and libre=1;");
        while (rs.next()) {
            v3 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(valorFactVenta) as id_t from FacturasVentas where year(fechafactVenta)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=4 and libre=1;");
        while (rs.next()) {
            v4 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(valorFactVenta) as id_t from FacturasVentas where year(fechafactVenta)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=5 and libre=1;");
        while (rs.next()) {
            v5 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(valorFactVenta) as id_t from FacturasVentas where year(fechafactVenta)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=6 and libre=1;");
        while (rs.next()) {
            v6 = rs.getFloat("id_t");
        }
        vt=v1+v2+v3+v4+v5+v6;
        lblLibreIngresos.setText("" + vt);
        
        
        rs = stmt.executeQuery("select sum(subtotal) as id_t from FacturasCompras where year(fechaFactCompra)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=1 and libre=1;");
        while (rs.next()) {
            c1 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(subtotal) as id_t from FacturasCompras where year(fechaFactCompra)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=2 and libre=1;");
        while (rs.next()) {
            c2 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(subtotal) as id_t from FacturasCompras where year(fechaFactCompra)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=3 and libre=1;");
        while (rs.next()) {
            c3 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(valorFactCompra) as id_t from FacturasCompras where year(fechaFactCompra)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=4 and libre=1;");
        while (rs.next()) {
            c4 = rs.getFloat("id_t");
        }
        rs = stmt.executeQuery("select sum(valorFactCompra) as id_t from FacturasCompras where year(fechaFactCompra)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoFact=5 and libre=1;");
        while (rs.next()) {
            c5 = rs.getFloat("id_t");
        }
        ct=c1+c2+c3+c4+c5;
        lblLibreEgresos.setText("" + ct);
        
        rs = stmt.executeQuery("select sum(sueldo) as id_t from Ingresos where año=" + String.valueOf(this.comboAño.getSelectedItem()) + ";");
        while (rs.next()) {
            c5 = rs.getFloat("id_t");
        }
        lblSueldoTotalIng.setText(""+c5);
        rs = stmt.executeQuery("select sum(aporteIESS) as id_t from Ingresos where año=" + String.valueOf(this.comboAño.getSelectedItem()) + ";");
        while (rs.next()) {
            c5 = rs.getFloat("id_t");
        }
        lblSueldoTotalEgre.setText(""+c5);
        
        
        rs = stmt.executeQuery("select sum(valorFactCompra) as id_t from FacturasCompras where year(fechaFactCompra)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoGastoFactCompra='Educación';");
        while (rs.next()) {
            c5 = rs.getFloat("id_t");
        }
        lblEducacion.setText(""+c5);
        rs = stmt.executeQuery("select sum(valorFactCompra) as id_t from FacturasCompras where year(fechaFactCompra)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoGastoFactCompra='Salud';");
        while (rs.next()) {
            c5 = rs.getFloat("id_t");
        }
        lblSalud.setText(""+c5);
        rs = stmt.executeQuery("select sum(valorFactCompra) as id_t from FacturasCompras where year(fechaFactCompra)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoGastoFactCompra='Alimentación';");
        while (rs.next()) {
            c5 = rs.getFloat("id_t");
        }
        lblAlimentacion.setText(""+c5);
        rs = stmt.executeQuery("select sum(valorFactCompra) as id_t from FacturasCompras where year(fechaFactCompra)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoGastoFactCompra='Vivienda';");
        while (rs.next()) {
            c5 = rs.getFloat("id_t");
        }
        lblVivienda.setText(""+c5);
        rs = stmt.executeQuery("select sum(valorFactCompra) as id_t from FacturasCompras where year(fechaFactCompra)=" + String.valueOf(this.comboAño.getSelectedItem()) + " and tipoGastoFactCompra='Vestimenta';");
        while (rs.next()) {
            c5 = rs.getFloat("id_t");
        }
        lblVestimenta.setText(""+c5);
        
        
        
        rs = stmt.executeQuery("select sum(impuestoRenta) as id_t from Ingresos where año=" + String.valueOf(this.comboAño.getSelectedItem()) + ";");
        while (rs.next()) {
            c5 = rs.getFloat("id_t");
        }
        lblRentaSueldo.setText(""+c5);
    } catch (SQLException ex) {
        System.out.println("SQLException: " + ex.getMessage());
        System.out.println("SQLState: " + ex.getSQLState());
        System.out.println("VendorError: " + ex.getErrorCode());
    } finally {
        if (rs != null) {
            try {
                rs.close();
            } catch (SQLException sqlEx) {
            } // ignore 

            rs = null;
        }
        if (stmt != null) {
            try {
                stmt.close();
            } catch (SQLException sqlEx) {
            } 
            stmt = null;
        }
    }
}//GEN-LAST:event_btnCacularActionPerformed

    private void btnFactVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactVentasActionPerformed
        this.setVisible(false);
        IngresarFacturasVentas a = new IngresarFacturasVentas();
        a.setVisible(true);
    }//GEN-LAST:event_btnFactVentasActionPerformed

    private void btnFactComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactComprasActionPerformed
        this.setVisible(false);
        IngresarFacturasCompra a = new IngresarFacturasCompra();
        a.setVisible(true);
    }//GEN-LAST:event_btnFactComprasActionPerformed

    private void btnCalcularIVA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIVA3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Ingresos a = new Ingresos();
        a.setVisible(true);
    }//GEN-LAST:event_btnCalcularIVA3ActionPerformed

    private void btnCalcularIVA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIVA6ActionPerformed
        this.setVisible(false);
        CalculoIva a = new CalculoIva();
        a.setVisible(true);
    }//GEN-LAST:event_btnCalcularIVA6ActionPerformed

    private void btnCalcularIVA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIVA7ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CalculoImpuestoRenta a = new CalculoImpuestoRenta();
        a.setVisible(true);
    }//GEN-LAST:event_btnCalcularIVA7ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCacular;
    private javax.swing.JButton btnCalcularIVA3;
    private javax.swing.JButton btnCalcularIVA6;
    private javax.swing.JButton btnCalcularIVA7;
    private javax.swing.JButton btnFactCompras;
    private javax.swing.JButton btnFactVentas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox comboAño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel lblAlimentacion;
    private javax.swing.JLabel lblEducacion;
    private javax.swing.JLabel lblEgresos;
    private javax.swing.JLabel lblIngresos;
    private javax.swing.JLabel lblLibreEgresos;
    private javax.swing.JLabel lblLibreIngresos;
    private javax.swing.JLabel lblRentaSueldo;
    private javax.swing.JLabel lblSalud;
    private javax.swing.JLabel lblSueldoTotalEgre;
    private javax.swing.JLabel lblSueldoTotalIng;
    private javax.swing.JLabel lblVB2;
    private javax.swing.JLabel lblVB4;
    private javax.swing.JLabel lblVestimenta;
    private javax.swing.JLabel lblVestimenta1;
    private javax.swing.JLabel lblVivienda;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
